### ISSUE TITLE
Idea: Change base select to react-select

### ISSUE THREAD

**Issue by blazej-bryla** [patryk-penczek/spacenews#2]
### Hi @patryk-penczek !
I saw your project and find simply improvement.
You using base select for filter by category.
I found pretty good library that can improve UX on SpaceNews!
Check out [react-select](https://react-select.com/home), if you encounter any problem write to me, I will be glad to help you!

**Comment by patryk-penczek** [comment]
Hi @blazej-bryla ,

Thank you for your feedback! I appreciate your suggestion regarding the use of `react-select` to improve the UX on SpaceNews.

I have implemented your suggestion and made the necessary changes using the `react-select` package - [Pull request](https://github.com/patryk-penczek/spacenews/pull/3).

If you have any further suggestions or encounter any issues with the implementation, please let me know. I would be glad to receive your assistance or feedback.

Best regards,
Patryk Penczek

**Comment by blazej-bryla** [comment]
Good job @patryk-penczek ! ✅
